name: Deployment pipeline

on:
  push:
    branches:
      - master   
  pull_request:
    branches: [master]   
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install front
        run: npm install ./front-end  
      - name: npm install back
        run: npm install
      - name: lint
        run: npm run lint .
      - name: build
        run: cd ./front-end && npm run build
      - name: deploy
        if: ${{ github.event_name == 'push' && ( ! contains(join(toJson(github.event.commits.*.message)), '#skip') ) }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: http://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health
          rollbackonhealthcheckfailed: true
      - name: success on deploy
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && ( ! contains(join(toJson(github.event.commits.*.message)), '#skip') ) }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
